# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_intrinsics"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "module of text descriptions of Fortran intrinsics and features"
categories = ["Fortran Intrinsic descriptions"]
keywords = ["fortran", "manpages", "intrinsics"]
homepage = "https://github.com/urbanjost/M_intrinsics.git"

[build]
auto-executables = true
auto-tests = true
auto-examples = false

[[executable]]
name="bull"
source-dir="app"
main="main.f90"
[dependencies]
M_CLI2        =  {  git  =  "https://github.com/urbanjost/M_CLI2.git"        }
M_match       =  {  git  =  "https://github.com/urbanjost/M_match.git"       }
M_strings     =  {  git  =  "https://github.com/urbanjost/M_strings.git"     }
M_escape      =  {  git  =  "https://github.com/urbanjost/M_escape.git"      }
